# Generated by Django 3.1.3 on 2020-11-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('unq_id', models.CharField(max_length=255)),
                ('contact_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('emailAddr', models.CharField(max_length=200, unique=True)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('last_login', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('mobileNumber', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('auth_token', models.CharField(max_length=200)),
                ('token_expiry', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SharedTasks',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('task_id', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('cate_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('dueDate', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
    ]
